### ISSUE TITLE
Switch to newes version of Nextcloud

### ISSUE THREAD

**Issue by brejoc** [brejoc/docker-owncloud#14]
This docker image is using a rather old version of OwnCloud. This should be switched to the newest version of Nextcloud: https://nextcloud.com/install/#instructions-server

**Comment by arpitbatra123** [comment]
Hi, I have made a pull request to solve the issue. But i have one concern regarding the issue. In the issue you stated that the docker image should use the newest version of OwnCloud. However The URL you provided is of Nextcloud. Nevertheless i assumed you meant owncloud and went ahead to the owncloud site to locate the newest version and update the dockerfile accordingly.

**Comment by arpitbatra123** [comment]
Please Check #16 .

**Comment by arpitbatra123** [comment]
Please Check #16 again. Image Builds Succesfully Now.

**Comment by arpitbatra123** [comment]
Please Check #16 . I made the required changes.

**Comment by arpitbatra123** [comment]
Please Check #16  . I made the required changes.
